name: RickROP
main: me.BingoRufus.RickROP.Main
descripton: Rick Roll Players Asking for OP
version: 1.2.0
api-version: 1.13
author: BingoRufus
commands:
  rickrop:
    description: Commands for RickROP

permissions:
  rickrop.*:
   description: Parent to all RickROP nodes
   children:
     rickrop.command:
       description: Rick Roll the players yourself
       default: false
     rickrop.exclude:
       description: Excludes players from being Rick Rolled
       default: false
     rickrop.reload:
       description: Reload the Config
       default: false