name: RickROP
main: me.BingoRufus.RickROP.Main
description: Rick Roll Players Asking for OP
version: 1.3.0
api-version: 1.13
author: BingoRufus
commands:
  rickrop:
    description: Commands for RickROP

permissions:
  rickrop.*:
   description: Parent to all RickROP nodes
   children:
     rickrop.play.*:
       description: Play RickROP songs
       default: false
       children:
         rickrop.play.rickroll:
           description: Rickroll players
           default: false
         rickrop.play.crabrave:
           description: Play Crabrave
           default: false
         rickrop.play.random:
           description: Play a random RickROP song
           default: false
     rickrop.exclude:
       description: Excludes players from being Rick Rolled
       default: false
     rickrop.reload:
       description: Reload the Config
       default: false
     rickrop.seeblocked:
       description: See Blocked Messages
       default: false