name: RickROP
main: me.BingoRufus.RickROP.Main
version: 1.0.1
api-version: 1.13
author: BingoRufus
descripton: Rick Roll Players Asking for OP
commands:
  rickroll:
    description: Rick Roll players yourself
    usage: /<command> [<player>]
permissions:
  rickrop.*:
   description: Parent to all RickROP nodes
   children:
     rickrop.command:
       description: Rick Roll the players yourself
       default: false
     rickrop.exclude:
       description: Excludes players from being Rick Rolled
       default: false